event_homepage:
    pattern:  /hello/{name}/{count}
    defaults: { _controller: EventBundle:Default:index }

EventBundle_event:
    resource: "@EventBundle/Resources/config/routing/event.yml"

event_report_updated_events:
    pattern: /events/report/recentlyUpdated.csv
    defaults: { _controller: EventBundle:Report:updatedEvents, _format: csv}