parameters:
#    event.example.class: Yoda\EventBundle\Example

services:
#    event.example:
#        class: %event.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    #can be anything
    yoda_event.reporting.event_report_manager:
         class: Yoda\EventBundle\Reporting\EventReportManager
         arguments:
            - "@doctrine.orm.entity_manager"
         calls:
            - [ setLogger, ["@logger"]]

    yoda_event.twig.event_extension:
         class: Yoda\EventBundle\Twig\EventExtension
         arguments: []
         tags:
             - { name: twig.extension }
