<?php
/**
 * Created by PhpStorm.
 * User: timbauer
 * Date: 7/7/14
 * Time: 3:43 PM
 */

namespace Yoda\EventBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Templating\TemplateReference;
use Symfony\Bundle\TwigBundle\Controller\ExceptionController as BaseExceptionController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Log\DebugLoggerInterface;
use Symfony\Component\HttpKernel\Exception\FlattenException;

class ExceptionController extends BaseExceptionController
{
    private $exceptionClass;

    public function showAction(Request $request, FlattenException $exception, DebugLoggerInterface $logger = null, $format = 'html')
    {
        $this->exceptionClass = $exception->getClass();

        return parent::showAction($request, $exception, $logger, $format);
    }

    protected function findTemplate(Request $request, $format, $code, $debug)
    {
        if (!$debug && $this->exceptionClass == 'Yoda\EventBundle\Exception\EventNotFoundException') {
            return 'EventBundle:Exception:error404.html.twig';
        }

        return parent::findTemplate($request, $format, $code, $debug); // TODO: Change the autogenerated stub
    }


} 